// AUTO-GENERATED by scripts/enrich_places.py – do not edit by hand.
// Run `python scripts/enrich_places.py` to regenerate with live Places API data.
import { Place } from "@/lib/types";

export type PlaceEnrichment = Partial<
  Pick<
    Place,
    | "placeId"
    | "rating"
    | "userRatingsTotal"
    | "priceLevel"
    | "phone"
    | "website"
    | "hours"
    | "aiDescription"
    | "photoUrl"
  >
>;

/** Keyed by `${category}:${id}`. */
export const enrichment: Record<string, PlaceEnrichment> = {};
